server:
  port: 9000
spring:
  application:
    name: spring-cloud-turbine-dashboard
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
turbine:
  appConfig: spring-cloud-consumer-server,spring-cloud-provider-server
  clusterNameExpression: "'default'"